### ISSUE TITLE
Trailing \ stripped when formatting in VS Code

### ISSUE THREAD

**Issue by jesse-sony** [EeyoreLee/vscode-extension-yapf#36]
This is a weird one.  Given this block of code
```
def __setProjAndEnv(self, project: str, env: str):
    with tryBlockSignals(self.__sw.envComboBox, self.__sw.projectComboBox), \
          waitCursor():
        pass
```
running YAPF through VS Code on Windows will strip out the trailing \\, making it invalid python code. running yapf -i from the command line does not have the same behavior. We're using a custom app path for YAPF set in the plugin config. Works fine on Linux

**Comment by EeyoreLee** [comment]
@jesse-sony - hi, how did you get your binary yapf ?  and you're using `yapf.interpreter` settings, right ?

**Comment by EeyoreLee** [comment]
@jesse-sony - I reproduct this issue just both yapf bundled and in location in windows. And I confirm that is yapf built-in issue. execute `type xx.py | yapf` in windows cmd can verity it. Cause I use stdin and stdout not yapf in-place, I can't fix it by my side, I will issue it to `google/yapf` repo and release it when yapf resolve it.

**Comment by jesse-sony** [comment]
doesn't seem like it matters, but yes we're using `yapf.path` and we built our own yapf package which we distribute internally.
If I have some time I'll poke around in the yapf internals and see if I can figure out what is happening. My initial thought was the Windows shell was stripping it out, but doing `type test1.py > test2.py` does not remove it, so it does somehow seem to be related to how yapf is reading from stdin

**Comment by jesse-sony** [comment]
Looks like you pushed up a PR to fix it. I merged it into our branch of yapf and it is working. thank you!

**Comment by EeyoreLee** [comment]
@jesse-sony - it's nice that you have your own yapf replica can merge this PR priority. But it seems you didn't use `yapf.path` successful cause I will do something like this PR to `google/yapf` on the extension side.  Could you give me a rough idea of how you build a binary package then I can reproduct the same situation for me and comfirm what's happened here. cause `google/yapf` didn't provide a offical tutorial to build a yapf binary.

**Comment by EeyoreLee** [comment]
@jesse-sony - thanks so much. I reproduct it through this approach. The reason is windows stdin buffer will auto replace `\n` to `\r\n`, so altought I already replace `\r\n` to `\n`, yapf will still get `\r\n` raw. And if I don't do that, don't replace `\r\n` to `\n`， windows stdin buffer will change it to `\r\r\n` then raise a python syntax error.  Friendly to Windows users but Windows developer. In short, the only way to fix it is like the PR I issue to `google/yapf`. Thanks for your help again.

**Comment by jesse-sony** [comment]
@EeyoreLee Thank YOU so much for the quick fix.
